accounts/urls.py
from django.urls import re_path
from . import views
app_name = 'accounts'
urlpatterns = [
  re_path('signup/', views.signup_view, name="signup"),
  re_path(r'^login/$', views.login_view, name="login"),
  re_path(r'^logout/$', views.logout_view, name="logout")
]

api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('arts/', views.articles, name='articles'),
    path('artdetails/', views.article_detail, name='article_detail'),
]

articles/urls.py
from django.urls import re_path
from django.conf.urls import url
from . import views
app_name='articles'
urlpatterns = [
  url(r'^$', views.article_list,name="list"),
  re_path('create/', views.article_create, name="create"),
  url(r'^(?P<slug>[\w-]+)/$', views.article_detail,name="detail")
]

myblog/urls.py
from django.contrib import admin
from django.conf.urls import url,include
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf.urls.static import static
from django.conf import settings
from articles import views as article_views
from django.urls import re_path

urlpatterns = [
    url('admin/', admin.site.urls),
    url('about/',views.about),
    url('homepage/',views.homepage),
    url('articles/',include('articles.urls')),
    re_path(r'^$', article_views.article_list, name='home'),
    url('accounts/', include('accounts.urls')),
    url('api/', include('api.urls'))
]

urlpatterns += staticfiles_urlpatterns()
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.db import models

# Create your models here.

api/models.py
from django.db import models

# Create your models here.

articles/models.py
from django.db import models
from django.contrib.auth.models import User

class Article(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, default=None)
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    body = models.TextField()
    date = models.DateTimeField(auto_now_add=True)
    thumb = models.ImageField(default='default.png', blank=True)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body
    objects = models.Manager()

articles/forms.py
from django import forms
from . import models

class CreateArticle(forms.ModelForm):
  class Meta:
    model = models.Article
    fields = ['title', 'body', 'slug', 'thumb']

accounts/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm,AuthenticationForm
from django.shortcuts import redirect
from django.views.decorators.csrf import csrf_exempt
from django.contrib.auth import login , logout

@csrf_exempt
def signup_view(request):
  if request.method == 'POST':
    signupForm = UserCreationForm(request.POST)
    if signupForm.is_valid():
      user = signupForm.save()
      # log the user in
      login(request, user)
      return redirect('articles:list')
  else:
    signupForm = UserCreationForm()
  return render(request, 'accounts/signup.html', {'form': signupForm})

def login_view(request):
  if request.method == 'POST':
    loginForm = AuthenticationForm(data=request.POST)
    if loginForm.is_valid():
      # log in the user
      user = loginForm.get_user()
      login(request, user)
      if 'next' in request.POST:
        return redirect(request.POST.get('next'))
      else:
        return redirect('articles:list')
  else:
    loginForm = AuthenticationForm()
  return render(request, 'accounts/login.html', {'login_Form': loginForm})

def logout_view(request):
  if request.method == 'POST':
    logout(request)
    return redirect('articles:list')

api/views.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from articles.models import Article
from django.core import serializers
from django.http import HttpResponse

def articles(request):
    articles = Article.objects.all().order_by('date')
    article_list = serializers.serialize('json', articles)
    return HttpResponse(article_list, content_type="text/json-comment-filtered")

def article_detail(request, slug):
  detailed_article = Article.objects.get(slug=slug)
  article_detail = serializers.serialize('json', detailed_article)
  return HttpResponse(article_detail, content_type="text/json-comment-filtered")

articles/views.py
from django.shortcuts import render
from .models import Article
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect
from . import forms

def article_list(request):
    articles = Article.objects.all().order_by('date')
    return render(request, 'articles/article_list.html', {'articles': articles})

def article_detail(request, slug):
  detailed_article = Article.objects.get(slug=slug)
  return render(request, 'articles/article_detail.html', {'article2': detailed_article})

@login_required(login_url="/accounts/login/")
def article_create(request):
  if request.method == 'POST':
    article_form = forms.CreateArticle(request.POST, request.FILES)
    if article_form.is_valid():
      instance = article_form.save(commit=False)
      instance.author = request.user
      instance.save()
      return redirect('articles:list')
  else:
    article_form = forms.CreateArticle()
  return render(request, 'articles/article_create.html', {'articleForm': article_form})

myblog/views.py
from django.http import HttpResponse
from django.shortcuts import render

def homepage(request):
    #return HttpResponse('This is Homepage')
    return render(request,'homepage.html')
def about(request):
    #return HttpResponse("About : Prosenjith Roy Shuvo")
    return render(request,'about.html')

accounts/templates/accounts/login.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Log in</h1>
  <form class="site-form" action="{% url 'accounts:login' %}" method="post">
    {% csrf_token %}
    {{ login_Form }}
    {% if request.GET.next %}
      <input type="hidden" name="next" value="{{ request.GET.next }}">
    {% endif %}
    <input type="submit" value="Login">
  </form>
{% endblock %}

accounts/templates/accounts/signup.html
{% extends 'base_layout.html' %}

{% block content %}
  <h1>Sign Up</h1>
  <form class="site-form" action="/accounts/signup/" method="post">
    {% csrf_token %}
    {{ form }}
    <input type="submit" value="Sign Up">
  </form>
{% endblock %}

articles/templates/articles/article_create.html
{% extends 'base_layout.html' %}
{% block content %}
<div class="create-article">
  <h2>Create an awesome new article.</h2>
  <form class="site-form" action="{% url 'articles:create' %}" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ articleForm }}
    <input type="submit" value="create">
  </form>
</div>
<script src="/static/slugify.js"></script>
{% endblock %}

articles/templates/articles/article_detail.html
{% extends 'base_layout.html' %}

{% block content %}
<div class="article-detail">
  <div class="article">
    <img src="{{ article2.thumb.url }}" />
    <h2>{{ article2.title }}</h2>
    <p>{{ article2.body }}</p>
    <p>{{ article2.date }}</p>
  </div>
</div>
{% endblock %}

articles/templates/articles/article_list.html
{% extends 'base_layout.html' %}

{% block content %}
<h1>Article list</h1>
<div class="articles">
    {% for article in articles %}
    <div class="article">
        <p class=”author”>added by {{ article.author.username }}</p>.
        <h2><a href="{% url 'articles:detail' slug=article.slug %}">{{ article.title}}</a></h2>
        <p>{{ article.snippet | truncatechars:50 }}</p>
        <p>{{ article.date }}</p>
    </div>
    {% endfor %}
</div>
{% endblock %}

templates/about.html
<!DOCTYPE html>
<html>
    <head>
        <title>About</title>
    </head>
    <body>
        <h1>This is Aboutpage</h1>
        <p>Hi,My name is Prosenjith Roy Shuvo and I love Django!</p>
    </body>
</html>

templates/base_layout.html
{% load static %}
<!DOCTYPE html>
<html>
<head>
        <title>Articles</title>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <meta name="keywords" content="footer, address, phone, icons" />
        <link rel="stylesheet" href="{% static 'styles.css' %}">
        <link rel="stylesheet" href="{% static 'footer.css' %}">
        <!--<link rel="stylesheet" href="{% static 'navbar.css' %}">-->
        <link rel="stylesheet" href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css">
        <link href="http://fonts.googleapis.com/css?family=Cookie" rel="stylesheet" type="text/css">
</head>

<body>
        <!--{% include 'parts/navbar.html' %}-->
        {% include 'parts/header.html' %}
        <div class="wrapper">
                {% block content %}
                {% endblock %}
        </div>
        {% include 'parts/footer.html' %}
</body>

templates/homepage.html
<!DOCTYPE html>
<html>
    <head>
        <title>Homepage</title>
    </head>
    <body>
        <h1>This is Homepage</h1>
        <p>Welcome to myblog!</p>
    </body>
</html>

templates/parts/footer.html
{% load static %}
<footer class="footer-distributed">
    <hr style = "color: blue;">
    <div class="footer-left">
        <img src="{% static 'logo.png' %}" />
        <h3>Spiritual <span>Programmer</span></h3>

        <p class="footer-links">
            <a href="#">Home</a>
            |
            <a href="#">Blog</a>
            |
            <a href="#">About</a>
            |
            <a href="#">Contact</a>
        </p>

        <p class="footer-company-name">@ 2019 Copyright: spiritualprogrammer.com</p>
    </div>

    <div class="footer-center">
        <div>
            <i class="fa fa-map-marker"></i>
            <p><span>Nadda,
                    Kalachandpur</span>
                Gulshan-02, Dhaka-1200</p>
        </div>

        <div>
            <i class="fa fa-phone"></i>
            <p>+880 1781-995745</p>
        </div>
        <div>
            <i class="fa fa-envelope"></i>
            <p><a href="mailto:prshuvo1971@gmail.com">prshuvo1971@gmail.com</a></p>
        </div>
    </div>
    <div class="footer-right">
        <p class="footer-company-about">
            <span>About Me</span>
            I'm a self-taught passionate programmer and software developer.
            At the same time I'm a spiritual person too.
            To me,Spirituality is being aware of the Spirit(Atman)</p>
        <div class="footer-icons">
            <a href="#"><i class="fa fa-facebook"></i></a>
            <a href="#"><i class="fa fa-twitter"></i></a>
            <a href="#"><i class="fa fa-instagram"></i></a>
            <a href="#"><i class="fa fa-linkedin"></i></a>
            <a href="#"><i class="fa fa-youtube"></i></a>
        </div>
    </div>
</footer>

templates/parts/header.html
{% load static %}
<header class="wrapper">
    <h1><a href="{% url 'home' %}"></a>Spiritual Programmer</h1>
    <!--<img src="{% static 'Django.png' %}" />-->
    <nav>
        <ul>
            {% if user.is_authenticated %}
            <li>
                <form class="logout-link" action="{% url 'accounts:logout' %}" method="POST">
                    {% csrf_token %}
                    <button type="submit">Logout</button>
                </form>
            </li>
            <li><a href="{% url 'articles:create' %}" class="highlight">New Article</a></li>
            {% else %}
            <li><a href="{% url 'accounts:signup' %}">Home</a></li>
            <li><a href="{% url 'accounts:login' %}">About</a></li>
            <li><a href="{% url 'accounts:signup' %}">Contact</a></li>
            <li><a href="{% url 'accounts:login' %}">Login</a></li>
            <li><a href="{% url 'accounts:signup' %}">Sign Up</a></li>      
            {% endif %}
        </ul>
    </nav>
</header>

templates/parts/navbar.html
<!DOCTYPE html>
<html>
<head>
<style>
body {margin:0;}

ul {
  list-style-type: none;
  margin: 0;
  padding: 0;
  overflow: hidden;
  background-color: #333;
  position: fixed;
  top: 0;
  width: 100%;
}

li {
  float: left;
}

li a {
  display: block;
  color: white;
  text-align: center;
  padding: 14px 16px;
  text-decoration: none;
}

li a:hover:not(.active) {
  background-color: #111;
}

.active {
  background-color: #4CAF50;
}
</style>
</head>
<body>

<ul>
  <li><a class="active" href="#home">Home</a></li>
  <li><a href="#news">News</a></li>
  <li><a href="#contact">Contact</a></li>
  <li><a href="#about">About</a></li>
</ul>

</body>
</html>